### ISSUE TITLE
Modelo de paso a tablas. Con N-N desarrolladas, etc.

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-servidor#11]

**Comment by fincamd** [comment]
No sé por qué ahora me parece que la relación entre actividad y material "usa" debería de ser también n-n.
Si no, no podríamos tener dos actividades usando el mismo material. O eso creo.

**Comment by AdrianPerezManso** [comment]
Esto es algo que se hablo en la reunión en la que se modeló la base de datos. La idea primera era que los materiales, aun siendo los mismos, se dividían en dos entradas distintas de la BD. Podemos cambiarlo, de todas formas, no creo que haya ningún inconveniente, además de que se reducirían potencialmente el número de entradas en esta colección

**Comment by fincamd** [comment]
Otra cuestión va relacionada con el tema de los pagos. Puede que haya pagos en efectivo, tarjeta, transferencia, etc. Pero tenemos una 1-N en modo pago. Esto es lo que hay ahora:

![image](https://user-images.githubusercontent.com/37817126/88559785-93ccce00-d02d-11ea-9097-7cc88c4f6023.png)

Pero ahora mismo le estoy dando vueltas y no comprendo para qué sirve esa tabla de modo_pago. Se relaciona con un taller (es decir, actividad impartida por un/a monitor/a). Pero entonces cuando un cliente vaya a contratar un programa, ya le viene un pago predefinido.

Creo que hay dos vías por las que se puede llegar a lo que tenemos ya en el diagrama. Son:
1. Que el modo_pago restrinja la forma de abonar el importe de la clase.
2. Que la entidad modo_pago no esté bien pensada y/o relacionada con el resto de entidades. ¿El importe de los talleres dónde lo registramos? Quizá es esta entidad la que pensamos que debería recoger esa información.ç

Quizás habría que añadir un campo a taller (actividad + monitor) y agregarle el importe por cliente. Y mover el modo_pago a la relación de apuntado (cliente + programa).

Quizás son muchas cosas de una vez. Si no me he explicado bien házmelo saber jejeje

**Comment by fincamd** [comment]
> Esto es algo que se hablo en la reunión en la que se modeló la base de datos. La idea primera era que los materiales, aun siendo los mismos, se dividían en dos entradas distintas de la BD. Podemos cambiarlo, de todas formas, no creo que haya ningún inconveniente, además de que se reducirían potencialmente el número de entradas en esta colección

Por cierto, esto que mencionas quedaría así:

![image](https://user-images.githubusercontent.com/37817126/88561350-94fefa80-d02f-11ea-8167-21090a64fbfc.png)

¿Visto bueno?

**Comment by AdrianPerezManso** [comment]
Visto bueno al cambio de la relación entre Actividad y Material. 

En cuanto al "modo de pago": eso surgió por cómo estaban dispuestos los pagos **a los monitores**, nada que ver con el cobro del taller a los clientes. Se propuso esto debido a que a cada monitor se le paga de distinta manera. Por ejemplo, unos cobran por una cantidad de horas impartida y otros por el número de niños en la actividad. El campo valor es la cantidad a pagar, que luego sería computada junto al número de horas o al número de clientes.
