### ISSUE TITLE
Modificar todo lo relacionado con la base de datos para añadir sistema de usuarios

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-servidor#18]

**Comment by fincamd** [comment]
A la espera de que se determinen los nombres de usuario en #19. También se debería concretar qué se guarda de los usuarios para identificarles. Id mínimo, email?, username?, password cifrada?, etc.

@AdrianPerezManso

**Comment by AdrianPerezManso** [comment]
En cuanto a los nombres creo que podemos optar por el nombre propio del administrador para este usuario, y la otra cuenta algo como "actividades" o similar.

Respecto a la información a guardar, creo que es suficiente registrar el nombre de usuario y la contraseña cifrada, dado que no habrá opción de creación de usuarios, ni que tengan relación con los correos electrónicos

**Comment by AdrianPerezManso** [comment]
He hablado con el PO y me ha dicho que la zona se llama "coworking" o sea que podríamos optar por "zonacw" o algo por el estilo

**Comment by fincamd** [comment]
> He hablado con el PO y me ha dicho que la zona se llama "coworking" o sea que podríamos optar por "zonacw" o algo por el estilo

No he entendido a qué te refieres... ¿Quizás al campo en actividad? ¿O otra cosa?

**Comment by AdrianPerezManso** [comment]
> > He hablado con el PO y me ha dicho que la zona se llama "coworking" o sea que podríamos optar por "zonacw" o algo por el estilo
> 
> No he entendido a qué te refieres... ¿Quizás al campo en actividad? ¿O otra cosa?

Al nombre del usuario no principal

**Comment by fincamd** [comment]
Se necesitan dos roles de usuario por el momento. "Main" y "Secondary". Los usuarios van a tener nombre de usuario y contraseña cifrada.
