### ISSUE TITLE
Determinar: Tipos de usuarios y restricciones de cada uno (Hablar con Product Owner)

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-servidor#19]

**Comment by AdrianPerezManso** [comment]
La reunión ya ha tenido lugar, y se ha establecido los siguientes usuarios por el momento:
* El usuario principal tendrá acceso pleno a toda la información y todas las características de la aplicación
* Otro tipo de usuario podrá ver las actividades y talleres que se realzarán a la vez que los clientes/niños apuntados a dichas actividades. La idea de este usuario es monitorizar que los niños de cada taller concuerdan con los apuntados, por lo tanto se concreta el ámbito de trabajo para este usuario, sin tener acceso a otras funcionalidades del sistema como pagos a realizar, fichas de clientes/actividades, etc.

Los nombres de los usuarios aún están por determinar. De la misma manera, se dejá abierta la posibilidad de introducir nuevos tipos de usuarios si el Product Owner así lo requiere.

**Comment by fincamd** [comment]
Le pongo un pin para que sea más fácil encontrarla luego a la hora de programar los usuarios.
