### ISSUE TITLE
Crear fábrica de entidades para la API

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-servidor#28]
Crear capa de indirección entre las rutas de la API y el gestor de la base de datos, que junto a la fachada, permitan evitar cambios en cascada si se modifica el modelo de dominio.

Relacionada con #13.

Se plantea mantener la Fachada lo más estable posible para evitar problemas si modificamos algo de la persistencia.

Ejemplo para nada ilustrativo:
![image](https://user-images.githubusercontent.com/37817126/88823682-a37f1a80-d1c5-11ea-941f-feebd3320f1d.png)

**Comment by AdrianPerezManso** [comment]
Queda por ver si esta fábrica se modifica o no en el futuro pero por el momento, la marcamos como acabada.
