### ISSUE TITLE
Descentralizar las importaciones de la aplicación

### ISSUE THREAD

**Issue by AdrianPerezManso** [SmallDreamDev/small-dream-servidor#29]
Ahora mismo todos los imports se realizan en App.js, donde se inicializan y son distribuidos a distintos módulos. Igual podemos cambiar esto, haciendo que los imports estén en el lugar donde se utilicen, liberando a App.js de la responsabilidad de inicializar módulos que no usa de manera directa.

Qué opinas @fincamd?

**Comment by fincamd** [comment]
Hombre, yo creo que sería contraproducente. Puede que muchos módulos lleguen a utilizar un mismo import. 

Si este import es un objeto o algo del estilo que requiera inicializarse, tendríamos que buscar la forma de que la instancia persista. Si no, podríamos perder el estado del objeto. Por ejemplo con la sesión de Express. 

Yo creo que es mejor manejar los imports en App.js y desde ahí decidir a quién le pasamos qué modulo. Recuerda que hay que unir los controladores a la app, junto con los routers para manejar permisos de sesión según el usuario y demás shenanigans (a los que además tendremos que pasarles módulos que se usarán en los controladores, etc.). Para eso necesitamos tener a la vista varios módulos. 

Si te parece que están hechos un desastre siempre se puede intentar colocarlos un poco comentando el código pero tampoco veo necesidad de complicarse tanto como para descentralizar los imports... Cómo lo ves @AdrianPerezManso ?

**Comment by AdrianPerezManso** [comment]
Vale, lo decía porque igual en el futuro hay demasiadas importaciones, pero podríamos hacer un _workaround_. Entonces lo dejamos como está.
