### ISSUE TITLE
Programar Update y Delete de entidades en el crud y en la API

### ISSUE THREAD

**Issue by fincamd** [SmallDreamDev/small-dream-servidor#34]

**Comment by AdrianPerezManso** [comment]
Además de acabar el Update y el Delete, se ha refactorizado rCrudEntity, ya que la respuesta en todos los _endpoints_ era similar. Ahora la función `responseFunction()` recibe los parámetros necesarios, como los códigos de estado HTTP, y mensajes de error, para enviar la respuesta.
